### ISSUE TITLE
udpate webpack-dev-server to resolve warning on `yarn install`

### ISSUE THREAD

**Issue by micahstubbs** [mapd/mapd3#10]

**Comment by jrajav** [comment]
Not that I'm against this, but is there any specific reason for this?

**Comment by clhenrick** [comment]
@micahstubbs noting that the `webpack-dev-server` is not being used anywhere as far as I can tell with mapd3 (check the `package.json` scripts). When developing and bundling `mapd3` only `webpack` is used. ([comment copied from here](https://github.com/mapd/mapd-immerse/issues/3937#issuecomment-368594707))

**Comment by micahstubbs** [comment]
@jrajav wanted to resolve a warning in the terminal to rule out a problem. found the problem root cause and it was not `webpack-dev-server` here.

@clhenrick good point.  I'll update this PR to remove `webpack-dev-server` as a `mapd3` dependency to avoid future confusion 😄

**Comment by clhenrick** [comment]
@micahstubbs it might be useful to keep it for the `examples` directory

**Comment by micahstubbs** [comment]
ah, so that's where we use it 💡
