### ISSUE TITLE
Downgrade Babel dev dependencies

### ISSUE THREAD

**Issue by clhenrick** [mapd/mapd3#37]
If mapd3 has been linked to Immerse using `npm link` or `yarn link`, the unit tests will fail to run in Immerse. In order to run the tests in Immerse you must unlink mapd3 and then re-install it from source which isn't ideal. This is due to Immerse using `babel-core@6.10.4` and mapd3 using `@babel/core@7.0.0-beta.36`. These versions seem to be incompatible with one another. To fix this we should downgrade Babel related dependencies to `6.10.x`.

**Comment by jrajav** [comment]
Do we know why Babel was upgraded to a beta version to begin with?

**Comment by biovisualize** [comment]
It's probably what got install when doing a generic babel upgrade.
